export const START_LOAD_SCORES = "START_LOAD_SCORES";
export const SCORES_LOADED = "SCORES_LOADED";

export const START_LOAD_PLAYERS = "START_LOAD_PLAYERS";
export const PLAYERS_LOADED = "PLAYERS_LOADED";